language: objective-c
before_install:
- nvm install stable
- nvm use stable
- wget http://dl.google.com/android/android-sdk_r24.4.1-macosx.zip
- unzip android-sdk_r24.4.1-macosx.zip
- export ANDROID_HOME=$PWD/android-sdk-macosx
- export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
- echo yes | android update sdk --filter platform-tools --no-ui --force > /dev/null
- echo yes | android update sdk --filter android-28 --no-ui --force > /dev/null
- echo yes | android update sdk --filter build-tools-28.0.3 --all --no-ui --force > /dev/null

install:
- npm install -g cordova
- npm install -g ionic
- gem install xcpretty

script:
- cd ..
- cordova create hello com.example.hello HelloWorld
- cd hello
- cordova platform add ios
- cordova platform add android
- cordova plugin add ../testfairy-cordova-plugin
- git apply ../testfairy-cordova-plugin/misc/cordova.patch
- cordova build ios | xcpretty
- cordova build android
- cd ..
- rm -rf hello
- ionic start myApp blank --cordova --no-link
- cd myApp
- ionic cordova platform add ios || true
- ionic cordova platform add android || true
- ionic cordova plugin add ../testfairy-cordova-plugin
- git apply ../testfairy-cordova-plugin/misc/ionic.patch
- touch resources/ios/splash/Default@2x~iphone.png
- touch resources/ios/splash/Default-Portrait~ipad.png
- touch resources/ios/splash/Default~iphone.png
- ionic build android || true
- ionic build ios | xcpretty || true
- cd ..
- rm -rf myApp
- cd testfairy-cordova-plugin

deploy:
  provider: npm
  email: support@testfairy.com
  api_key:
    secure: cAkxfGKlJCiDmoz/J7YyYwATNVvJDctygbiUJZi0gqAQnM96u61jkPt9cntoBFG+rlxQGdFNjYnt4sEwjDkgOk17mRsqZocjQFsIorKjT2TIB1nJmCt2CFyJCamyxjBRxCrj0+MmlwYmHVnFPZ2vWOQ/HusBVQ5/ZSPO6wDBuXw=
  on:
    tags: true
    repo: testfairy/testfairy-cordova-plugin
